# ==========================================
# 1. THÔNG TIN K?T N?I DATABASE (POSTGRESQL)
# ==========================================
# ??a ch? nhà c?a Database: C?ng m?c ??nh là 5432. 
# L?u ý: vanh ph?i t?o s?n m?t database tr?ng tên là "tram_dac_san_db" trong pgAdmin tr??c nhé!
spring.datasource.url=jdbc:postgresql://localhost:5432/tram_dac_san

# Tên tài kho?n và M?t kh?u m? c?a (C?u t? ??i l?i cho kh?p v?i máy c?a c?u nha, th??ng m?c ??nh user là postgres)
spring.datasource.username=postgres
spring.datasource.password=vietanh2k5

# Ch? ??nh "ng??i lái xe" k?t n?i là PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# 2. C?U HÌNH HI?N TH? LOG (V? KHÍ ?? DEBUG)
# ==========================================
# B?t tính n?ng in các câu l?nh SQL ra màn hình Console (Gi?ng nh? g?n camera theo dõi xem code Java ?ang g?i l?nh gì xu?ng DB)
spring.jpa.show-sql=true

# S?p x?p câu l?nh SQL in ra cho ??p, có xu?ng dòng, th?t l? cho d? ??c
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# 3. QU?N LÝ T?O B?NG VÀ CH?Y FILE SQL (QUAN TR?NG)
# ==========================================
# Vì vanh ?ã t? vi?t tay file schema.sql c?c chu?n r?i, mình s? b?o Hibernate (th?ng hay lanh chanh t? t?o b?ng) là "none" (ng?i im), không ???c ghi ?è lên thi?t k? c?a c?u.
spring.jpa.hibernate.ddl-auto=none

# Ra l?nh cho Spring Boot t? ??ng ch?y 2 file schema.sql và data.sql m?i khi b?m nút Run d? án
spring.sql.init.mode=never